// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/nt/event/0x2dc.proto

package event

type TemplParam struct {
	Name  string `protobuf:"bytes,1,opt"`
	Value string `protobuf:"bytes,2,opt"`
	_     [0]func()
}

type GeneralGrayTipInfo struct {
	BusiType      int64         `protobuf:"varint,1,opt"`
	BusiId        int64         `protobuf:"varint,2,opt"`
	CtrlFlag      int32         `protobuf:"varint,3,opt"`
	C2CType       int32         `protobuf:"varint,4,opt"`
	ServiceType   int32         `protobuf:"varint,5,opt"`
	TemplId       int64         `protobuf:"varint,6,opt"`
	MsgTemplParam []*TemplParam `protobuf:"bytes,7,rep"`
	Content       []byte        `protobuf:"bytes,8,opt"`
	TipsSeqId     int64         `protobuf:"varint,10,opt"`
	PbReserv      []byte        `protobuf:"bytes,100,opt"`
}

type WithDrawWordingInfo struct {
	Int32ItemId int32  `protobuf:"varint,1,opt"`
	ItemName    string `protobuf:"bytes,2,opt"`
	_           [0]func()
}

type RedGrayTipsInfo struct {
	ShowLatest          uint32 `protobuf:"varint,1,opt"`
	SenderUin           uint64 `protobuf:"varint,2,opt"`
	ReceiverUin         uint64 `protobuf:"varint,3,opt"`
	SenderRichContent   string `protobuf:"bytes,4,opt"`
	ReceiverRichContent string `protobuf:"bytes,5,opt"`
	AuthKey             []byte `protobuf:"bytes,6,opt"`
	MsgType             int32  `protobuf:"zigzag32,7,opt"`
	LuckyFlag           uint32 `protobuf:"varint,8,opt"`
	HideFlag            uint32 `protobuf:"varint,9,opt"`
	LuckyUin            uint64 `protobuf:"varint,12,opt"`
}

type NotifyMsgBody struct {
	OptEnumType       int32                  `protobuf:"varint,1,opt"`
	OptGroupId        int64                  `protobuf:"varint,4,opt"`
	OptMsgGraytips    []byte                 `protobuf:"bytes,5,opt"`
	OptMsgRecall      *MessageRecallReminder `protobuf:"bytes,11,opt"`
	OptGeneralGrayTip []byte                 `protobuf:"bytes,26,opt"`
	OptMsgRedTips     *RedGrayTipsInfo       `protobuf:"bytes,9,opt"`
	OptReaction       *GroupReactionData0    `protobuf:"bytes,44,opt"`
	QqGroupDigestMsg  *QQGroupDigestMsg      `protobuf:"bytes,33,opt"`
	ServiceType       int32                  `protobuf:"varint,13,opt"`
}

type GroupReactionData0 struct {
	Data *GroupReactionData1 `protobuf:"bytes,1,opt"`
	_    [0]func()
}

type GroupReactionData1 struct {
	Data *GroupReactionData2 `protobuf:"bytes,1,opt"`
	_    [0]func()
}

type GroupReactionData2 struct {
	Target *GroupReactionTarget `protobuf:"bytes,2,opt"`
	Data   *GroupReactionData3  `protobuf:"bytes,3,opt"`
	_      [0]func()
}

type GroupReactionTarget struct {
	Seq int32 `protobuf:"varint,1,opt"`
	_   [0]func()
}

type GroupReactionData3 struct {
	Code        string `protobuf:"bytes,1,opt"`
	Count       int32  `protobuf:"varint,3,opt"`
	OperatorUid string `protobuf:"bytes,4,opt"`
	Type        int32  `protobuf:"varint,5,opt"` // 1 Add 2 Remove
	_           [0]func()
}

type QQGroupDigestMsg struct {
	GroupCode     uint64 `protobuf:"varint,1,opt"`
	Seq           uint32 `protobuf:"varint,2,opt"`
	Random        uint32 `protobuf:"varint,3,opt"`
	OpType        int32  `protobuf:"varint,4,opt"`
	Sender        string `protobuf:"bytes,5,opt"`
	DigestOper    string `protobuf:"bytes,6,opt"`
	OpTime        uint32 `protobuf:"varint,7,opt"`
	LastestMsgSeq uint32 `protobuf:"varint,8,opt"`
	OperNick      []byte `protobuf:"bytes,9,opt"`
	SenderNick    []byte `protobuf:"bytes,10,opt"`
	ExtInfo       int32  `protobuf:"varint,11,opt"`
}

type AIOGrayTipsInfo struct {
	OptUint32ShowLastest int32  `protobuf:"varint,1,opt"`
	OptBytesContent      []byte `protobuf:"bytes,2,opt"`
	OptUint32Remind      int32  `protobuf:"varint,3,opt"`
	OptBytesBrief        []byte `protobuf:"bytes,4,opt"`
	ReceiverUin          int64  `protobuf:"varint,5,opt"`
	ReliaoAdminOpt       int32  `protobuf:"varint,6,opt"`
	RobotGroupOpt        int32  `protobuf:"varint,7,opt"`
}

type MessageRecallReminder struct {
	Uid             string                               `protobuf:"bytes,1,opt"`
	Nickname        []byte                               `protobuf:"bytes,2,opt"`
	RecalledMsgList []*MessageRecallReminder_MessageMeta `protobuf:"bytes,3,rep"`
	ReminderContent []byte                               `protobuf:"bytes,4,opt"`
	Userdef         []byte                               `protobuf:"bytes,5,opt"`
	GroupType       int32                                `protobuf:"varint,6,opt"`
	OpType          int32                                `protobuf:"varint,7,opt"`
	AdminUid        string                               `protobuf:"bytes,8,opt"`
	MsgWordingInfo  *WithDrawWordingInfo                 `protobuf:"bytes,9,opt"`
}

type GroupMuteEvent struct {
	GroupUin    int64                         `protobuf:"varint,1,opt"`
	SubType     int32                         `protobuf:"varint,2,opt"`
	Field3      int32                         `protobuf:"varint,3,opt"`
	OperatorUid string                        `protobuf:"bytes,4,opt"`
	Data        *GroupMuteEvent_GroupMuteData `protobuf:"bytes,5,opt"`
	_           [0]func()
}

type MessageRecallReminder_MessageMeta struct {
	Seq        int32  `protobuf:"varint,1,opt"`
	Time       int32  `protobuf:"varint,2,opt"`
	MsgRandom  int32  `protobuf:"varint,3,opt"`
	MsgType    int32  `protobuf:"varint,4,opt"`
	MsgFlag    int32  `protobuf:"varint,5,opt"`
	AuthorUid  string `protobuf:"bytes,6,opt"`
	IsAnonyMsg int32  `protobuf:"varint,7,opt"`
	_          [0]func()
}

type GroupMuteEvent_GroupMuteData struct {
	Timestamp int32                                        `protobuf:"varint,1,opt"`
	Type      int32                                        `protobuf:"varint,2,opt"`
	State     *GroupMuteEvent_GroupMuteData_GroupMuteState `protobuf:"bytes,3,opt"`
	_         [0]func()
}

type GroupMuteEvent_GroupMuteData_GroupMuteState struct {
	TargetUid string `protobuf:"bytes,1,opt"`
	Duration  int32  `protobuf:"varint,2,opt"`
	_         [0]func()
}
